name: api_agent
description: Generate technology-agnostic api bindings for both client and server.
version: 0.6.2
repository: https://github.com/schultek/api_agent
issue_tracker: https://github.com/schultek/api_agent/issues

dependencies:
  analyzer: '>=5.11.0 <7.0.0'
  build: ^2.4.0
  collection: ^1.16.0
  dart_style: ^2.2.2
  http: ^1.2.0
  path: ^1.8.1
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  source_gen: ^1.2.1
  type_plus: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^3.0.0
  test: ^1.20.1

environment:
  sdk: '>=3.0.0 <4.0.0'
